name: Cypress Tests

on: [push]

jobs:
  e2e:
    name: Testing e2e
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3.5.2
      - name: Cypress run
        uses: cypress-io/github-action@v5.6.1
        with:
          start: yarn dev
